ledger/urls.py
from django.urls import path
from .views import RecipeDetailView, RecipeListView


urlpatterns = [
    path('recipes/list', RecipeListView.as_view(), name='recipes'),
    path('recipe/<int:pk>', RecipeDetailView.as_view(),
         name='recipe_details'),
]

app_name = 'ledger'

recipebook/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ledger.urls', namespace='ledger')),
    path('accounts/', include('django.contrib.auth.urls')),
]

ledger/models.py
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from datetime import datetime
from django.db import models
from django.urls import reverse


class Recipe(models.Model):
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    creation = models.DateTimeField(auto_now_add=True)
    updates = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('ledger:recipe_details', args=str(self.pk))
    

class Ingredient(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('ledger:ingredient_detail', args=str(self.pk))
    

class RecipeIngredient(models.Model):
    quantity = models.CharField(max_length=100)
    ingredient = models.ForeignKey(
        Ingredient, 
        on_delete=models.CASCADE, 
        related_name='recipe'
    )
    recipe = models.ForeignKey(
        Recipe, 
        on_delete=models.CASCADE, 
        related_name='ingredients'
    )
    
    def __str__(self):
        return '{} {} in {}'.format(
            self.quantity, self.ingredient.name, self.recipe.name
        )
        

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    short_bio = models.TextField(
        validators = [
            MinLengthValidator(255, "Your bio is too short. Input more data.")
        ]
    )

ledger/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import Recipe


class RecipeListView(ListView):
    model = Recipe
    template_name = 'recipe_list.html'
    

class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipe_details.html'

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> 
            {% block title %} Recipe Book {% endblock title %}
        </title>
        {% block styles %}
        {% endblock styles %}
    </head>
    <body>
        <h1>
            <a href={% url 'ledger:recipes' %}>Recipe Book</a>
        </h1>
        {% if request.user.is_authenticated %}
            <form action="{% url 'logout' %}" method="POST">
                {% csrf_token %}
                <button type="submit">Logout</button>
            </form>

        {% else %}
            {% if request.get_full_path != '/accounts/login/' %}
                <a href={% url 'login' %}>Login</a>
            {% endif %}

        {% endif %}
        <div id="content">
            {% block content %}
            {% endblock content %}
        </div>
        
        {% block scripts %}
        {% endblock scripts %}
    </body>
</html>

templates/recipe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> 
        Recipe Book 
    </title>
</head>
<body>
    <h1> 
        <a href = '/recipes/list'> 
            Recipe Book 
        </a> 
    </h1>
    <h2> 
        {{name}} 
    </h2>
    <h3>
        <ul>
            {% for ingredient in ingredients %}
            <li> 
                {{ingredient.quantity}} 
                {{ingredient.name}} 
            </li>
            {% endfor %}
        </ul>
    </h3>
</body>
</html>

templates/recipe_details.html
{% extends "base.html" %}
{% load static %}
{% block title %} {{ recipe.name }} {% endblock title %}
<h1>
    {{ recipe.name }}
</h1>
{% block content %}
    <h2>
        by {{ recipe.author }}
    </h2>
    <ul>
        {% for ingredient in recipe.ingredients.all %}
            <li>{{ ingredient.quantity }} {{ ingredient.ingredient.name }}</li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/recipe_list.html
{% extends "base.html" %}
{% load static %}
{% block title %} Recipe List {% endblock title %}
{% block content %}
    <h1>Recipe List</h1>
    <h2>
        <ul>
            {% for recipe in object_list %}
                <li>
                    <a href="{{ recipe.get_absolute_url }}">{{ recipe.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </h3>
{% endblock content %}

templates/recipes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> 
        Recipe Book 
    </title>
</head>
<body>
    <h1> 
        <a href = '/recipes/list'> 
            Recipe Book 
        </a> 
    </h1>
    <h2>
        <ul>
            {% for recipe in recipes %}
            <li> 
                <a href= "{{recipe.link}}" > 
                    {{recipe.name}} 
                </a> 
            </li>
            {% endfor %}
        </ul>
    </h2>
</body>
</html>